require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const bcrypt = require('bcryptjs');
const { sequelize, User, Patient, TriageAssessment, VitalSign, SymptomAnalysis, PriorityQueue, DoctorAssignment, Treatment, WaitTime, MedicalHistory, LabOrder, Medication, Discharge, EmergencyAlert, BedManagement, PatientFlow } = require('../models');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database reset and synced');

    // Users
    const hashedPassword = await bcrypt.hash('password123', 10);
    await User.bulkCreate([
      { email: 'admin@ertriage.com', password: hashedPassword, name: 'Dr. Sarah Admin', role: 'admin' },
      { email: 'doctor@ertriage.com', password: hashedPassword, name: 'Dr. James Wilson', role: 'doctor' },
      { email: 'nurse@ertriage.com', password: hashedPassword, name: 'Nurse Maria Garcia', role: 'nurse' },
      { email: 'reception@ertriage.com', password: hashedPassword, name: 'John Reception', role: 'receptionist' }
    ]);
    console.log('Users seeded');

    // 20 Patients
    const patients = await Patient.bulkCreate([
      { firstName: 'John', lastName: 'Smith', dateOfBirth: '1985-03-15', gender: 'Male', phone: '555-0101', email: 'john.smith@email.com', address: '123 Main St, Boston, MA', insuranceProvider: 'BlueCross', insuranceNumber: 'BC-123456', emergencyContact: 'Jane Smith', emergencyPhone: '555-0102', bloodType: 'A+', allergies: 'Penicillin', status: 'In Triage' },
      { firstName: 'Maria', lastName: 'Garcia', dateOfBirth: '1990-07-22', gender: 'Female', phone: '555-0103', email: 'maria.g@email.com', address: '456 Oak Ave, Boston, MA', insuranceProvider: 'Aetna', insuranceNumber: 'AE-789012', emergencyContact: 'Carlos Garcia', emergencyPhone: '555-0104', bloodType: 'O+', allergies: 'None', status: 'Waiting' },
      { firstName: 'Robert', lastName: 'Johnson', dateOfBirth: '1972-11-08', gender: 'Male', phone: '555-0105', email: 'r.johnson@email.com', address: '789 Pine Rd, Cambridge, MA', insuranceProvider: 'UnitedHealth', insuranceNumber: 'UH-345678', emergencyContact: 'Lisa Johnson', emergencyPhone: '555-0106', bloodType: 'B+', allergies: 'Sulfa drugs', status: 'In Treatment' },
      { firstName: 'Emily', lastName: 'Chen', dateOfBirth: '1995-01-30', gender: 'Female', phone: '555-0107', email: 'emily.chen@email.com', address: '321 Elm St, Somerville, MA', insuranceProvider: 'Cigna', insuranceNumber: 'CI-901234', emergencyContact: 'Wei Chen', emergencyPhone: '555-0108', bloodType: 'AB+', allergies: 'Latex', status: 'In Triage' },
      { firstName: 'Michael', lastName: 'Williams', dateOfBirth: '1968-05-17', gender: 'Male', phone: '555-0109', email: 'm.williams@email.com', address: '654 Maple Dr, Brookline, MA', insuranceProvider: 'Medicare', insuranceNumber: 'MC-567890', emergencyContact: 'Susan Williams', emergencyPhone: '555-0110', bloodType: 'O-', allergies: 'Aspirin, Codeine', status: 'Waiting' },
      { firstName: 'Sarah', lastName: 'Davis', dateOfBirth: '1988-09-03', gender: 'Female', phone: '555-0111', email: 's.davis@email.com', address: '987 Cedar Ln, Newton, MA', insuranceProvider: 'BlueCross', insuranceNumber: 'BC-234567', emergencyContact: 'Tom Davis', emergencyPhone: '555-0112', bloodType: 'A-', allergies: 'None', status: 'Registered' },
      { firstName: 'James', lastName: 'Brown', dateOfBirth: '1955-12-20', gender: 'Male', phone: '555-0113', email: 'j.brown@email.com', address: '147 Birch Ave, Quincy, MA', insuranceProvider: 'Medicare', insuranceNumber: 'MC-890123', emergencyContact: 'Mary Brown', emergencyPhone: '555-0114', bloodType: 'B-', allergies: 'Morphine', status: 'In Treatment' },
      { firstName: 'Jennifer', lastName: 'Martinez', dateOfBirth: '1992-04-11', gender: 'Female', phone: '555-0115', email: 'j.martinez@email.com', address: '258 Walnut St, Medford, MA', insuranceProvider: 'Aetna', insuranceNumber: 'AE-456789', emergencyContact: 'Pedro Martinez', emergencyPhone: '555-0116', bloodType: 'O+', allergies: 'Ibuprofen', status: 'Waiting' },
      { firstName: 'David', lastName: 'Anderson', dateOfBirth: '1979-08-25', gender: 'Male', phone: '555-0117', email: 'd.anderson@email.com', address: '369 Spruce Rd, Waltham, MA', insuranceProvider: 'UnitedHealth', insuranceNumber: 'UH-012345', emergencyContact: 'Karen Anderson', emergencyPhone: '555-0118', bloodType: 'AB-', allergies: 'None', status: 'In Triage' },
      { firstName: 'Lisa', lastName: 'Taylor', dateOfBirth: '1983-06-14', gender: 'Female', phone: '555-0119', email: 'l.taylor@email.com', address: '471 Ash Ct, Malden, MA', insuranceProvider: 'Cigna', insuranceNumber: 'CI-678901', emergencyContact: 'Mark Taylor', emergencyPhone: '555-0120', bloodType: 'A+', allergies: 'Erythromycin', status: 'Registered' },
      { firstName: 'Thomas', lastName: 'Wilson', dateOfBirth: '1960-02-28', gender: 'Male', phone: '555-0121', email: 't.wilson@email.com', address: '582 Poplar Blvd, Revere, MA', insuranceProvider: 'Medicare', insuranceNumber: 'MC-234567', emergencyContact: 'Patricia Wilson', emergencyPhone: '555-0122', bloodType: 'O+', allergies: 'Contrast dye', status: 'In Treatment' },
      { firstName: 'Amanda', lastName: 'Moore', dateOfBirth: '1997-10-07', gender: 'Female', phone: '555-0123', email: 'a.moore@email.com', address: '693 Hickory Way, Everett, MA', insuranceProvider: 'BlueCross', insuranceNumber: 'BC-345678', emergencyContact: 'Steve Moore', emergencyPhone: '555-0124', bloodType: 'B+', allergies: 'None', status: 'Waiting' },
      { firstName: 'Christopher', lastName: 'Jackson', dateOfBirth: '1975-03-19', gender: 'Male', phone: '555-0125', email: 'c.jackson@email.com', address: '804 Willow Ln, Chelsea, MA', insuranceProvider: 'Aetna', insuranceNumber: 'AE-567890', emergencyContact: 'Diana Jackson', emergencyPhone: '555-0126', bloodType: 'A+', allergies: 'Tetracycline', status: 'In Triage' },
      { firstName: 'Jessica', lastName: 'White', dateOfBirth: '1991-07-02', gender: 'Female', phone: '555-0127', email: 'j.white@email.com', address: '915 Chestnut Dr, Watertown, MA', insuranceProvider: 'UnitedHealth', insuranceNumber: 'UH-789012', emergencyContact: 'Brian White', emergencyPhone: '555-0128', bloodType: 'O-', allergies: 'Shellfish', status: 'Registered' },
      { firstName: 'Daniel', lastName: 'Harris', dateOfBirth: '1982-11-16', gender: 'Male', phone: '555-0129', email: 'd.harris@email.com', address: '126 Sycamore Ave, Arlington, MA', insuranceProvider: 'Cigna', insuranceNumber: 'CI-901234', emergencyContact: 'Rachel Harris', emergencyPhone: '555-0130', bloodType: 'AB+', allergies: 'Amoxicillin', status: 'Waiting' },
      { firstName: 'Ashley', lastName: 'Clark', dateOfBirth: '1999-05-24', gender: 'Female', phone: '555-0131', email: 'a.clark@email.com', address: '237 Magnolia St, Belmont, MA', insuranceProvider: 'BlueCross', insuranceNumber: 'BC-012345', emergencyContact: 'Mike Clark', emergencyPhone: '555-0132', bloodType: 'B-', allergies: 'None', status: 'In Treatment' },
      { firstName: 'Matthew', lastName: 'Lewis', dateOfBirth: '1970-09-08', gender: 'Male', phone: '555-0133', email: 'm.lewis@email.com', address: '348 Dogwood Rd, Lexington, MA', insuranceProvider: 'Medicare', insuranceNumber: 'MC-345678', emergencyContact: 'Sandra Lewis', emergencyPhone: '555-0134', bloodType: 'O+', allergies: 'NSAIDs', status: 'In Triage' },
      { firstName: 'Stephanie', lastName: 'Robinson', dateOfBirth: '1986-01-12', gender: 'Female', phone: '555-0135', email: 's.robinson@email.com', address: '459 Cypress Ct, Concord, MA', insuranceProvider: 'Aetna', insuranceNumber: 'AE-678901', emergencyContact: 'Kevin Robinson', emergencyPhone: '555-0136', bloodType: 'A-', allergies: 'Sulfonamides', status: 'Waiting' },
      { firstName: 'Andrew', lastName: 'Walker', dateOfBirth: '1963-04-06', gender: 'Male', phone: '555-0137', email: 'a.walker@email.com', address: '560 Redwood Blvd, Framingham, MA', insuranceProvider: 'UnitedHealth', insuranceNumber: 'UH-901234', emergencyContact: 'Nancy Walker', emergencyPhone: '555-0138', bloodType: 'AB+', allergies: 'Lidocaine', status: 'Registered' },
      { firstName: 'Nicole', lastName: 'Hall', dateOfBirth: '1994-08-19', gender: 'Female', phone: '555-0139', email: 'n.hall@email.com', address: '671 Palm Ave, Natick, MA', insuranceProvider: 'Cigna', insuranceNumber: 'CI-234567', emergencyContact: 'Greg Hall', emergencyPhone: '555-0140', bloodType: 'O+', allergies: 'None', status: 'In Treatment' }
    ]);
    console.log('Patients seeded');

    // 16 Triage Assessments
    await TriageAssessment.bulkCreate([
      { patientId: 1, chiefComplaint: 'Severe chest pain radiating to left arm', symptoms: 'Chest pain, shortness of breath, diaphoresis', painLevel: 9, onsetTime: '30 minutes ago', triageLevel: '2-Emergency', aiRecommendation: 'Immediate cardiac workup - possible MI', aiConfidence: 0.92, assessedBy: 3 },
      { patientId: 2, chiefComplaint: 'High fever with persistent cough', symptoms: 'Fever 103°F, productive cough, fatigue', painLevel: 4, onsetTime: '3 days', triageLevel: '3-Urgent', aiRecommendation: 'Respiratory panel and chest X-ray recommended', aiConfidence: 0.85, assessedBy: 3 },
      { patientId: 3, chiefComplaint: 'Fall from ladder - possible fracture', symptoms: 'Right arm pain, swelling, limited ROM', painLevel: 7, onsetTime: '1 hour ago', triageLevel: '3-Urgent', aiRecommendation: 'X-ray right upper extremity, assess neurovascular status', aiConfidence: 0.88, assessedBy: 3 },
      { patientId: 4, chiefComplaint: 'Severe abdominal pain', symptoms: 'RLQ pain, nausea, low-grade fever', painLevel: 8, onsetTime: '6 hours', triageLevel: '2-Emergency', aiRecommendation: 'CT abdomen - possible appendicitis', aiConfidence: 0.90, assessedBy: 3 },
      { patientId: 5, chiefComplaint: 'Diabetic emergency - very high blood sugar', symptoms: 'Confusion, extreme thirst, frequent urination', painLevel: 3, onsetTime: '2 hours', triageLevel: '2-Emergency', aiRecommendation: 'Stat glucose, BMP, start IV fluids', aiConfidence: 0.94, assessedBy: 3 },
      { patientId: 6, chiefComplaint: 'Migraine with visual disturbance', symptoms: 'Severe headache, aura, photophobia, nausea', painLevel: 8, onsetTime: '4 hours', triageLevel: '3-Urgent', aiRecommendation: 'Neurological assessment, CT head if first episode', aiConfidence: 0.82, assessedBy: 3 },
      { patientId: 7, chiefComplaint: 'Difficulty breathing - COPD exacerbation', symptoms: 'Wheezing, dyspnea, increased sputum production', painLevel: 5, onsetTime: '1 day', triageLevel: '2-Emergency', aiRecommendation: 'Nebulizer treatment, ABG, chest X-ray', aiConfidence: 0.91, assessedBy: 3 },
      { patientId: 8, chiefComplaint: 'Allergic reaction with facial swelling', symptoms: 'Facial edema, hives, throat tightness', painLevel: 3, onsetTime: '20 minutes ago', triageLevel: '1-Resuscitation', aiRecommendation: 'Immediate epinephrine, monitor airway', aiConfidence: 0.96, assessedBy: 3 },
      { patientId: 9, chiefComplaint: 'Lower back pain after lifting', symptoms: 'Lumbar pain, muscle spasm, limited mobility', painLevel: 6, onsetTime: '2 days', triageLevel: '4-Less Urgent', aiRecommendation: 'NSAIDs, muscle relaxant, follow up with PCP', aiConfidence: 0.87, assessedBy: 3 },
      { patientId: 10, chiefComplaint: 'Persistent nausea and vomiting', symptoms: 'Nausea, vomiting x8, dehydration', painLevel: 5, onsetTime: '12 hours', triageLevel: '3-Urgent', aiRecommendation: 'IV fluids, antiemetics, BMP for electrolytes', aiConfidence: 0.83, assessedBy: 3 },
      { patientId: 11, chiefComplaint: 'Sudden onset weakness on right side', symptoms: 'Right-sided weakness, slurred speech, facial droop', painLevel: 2, onsetTime: '45 minutes ago', triageLevel: '1-Resuscitation', aiRecommendation: 'STROKE ALERT - immediate CT, activate stroke team', aiConfidence: 0.97, assessedBy: 3 },
      { patientId: 12, chiefComplaint: 'Ankle sprain from sports', symptoms: 'Left ankle swelling, ecchymosis, pain with weight bearing', painLevel: 5, onsetTime: '3 hours', triageLevel: '4-Less Urgent', aiRecommendation: 'X-ray to rule out fracture, RICE protocol', aiConfidence: 0.89, assessedBy: 3 },
      { patientId: 13, chiefComplaint: 'Laceration on forearm', symptoms: 'Deep 4cm laceration, active bleeding', painLevel: 6, onsetTime: '30 minutes ago', triageLevel: '3-Urgent', aiRecommendation: 'Wound assessment, possible sutures, tetanus status', aiConfidence: 0.91, assessedBy: 3 },
      { patientId: 14, chiefComplaint: 'Urinary symptoms and flank pain', symptoms: 'Dysuria, frequency, right flank pain, hematuria', painLevel: 7, onsetTime: '1 day', triageLevel: '3-Urgent', aiRecommendation: 'UA, urine culture, CT KUB for possible kidney stone', aiConfidence: 0.86, assessedBy: 3 },
      { patientId: 15, chiefComplaint: 'Panic attack with palpitations', symptoms: 'Rapid heart rate, chest tightness, trembling, fear', painLevel: 4, onsetTime: '1 hour', triageLevel: '4-Less Urgent', aiRecommendation: 'ECG to rule out cardiac, benzodiazepine if needed', aiConfidence: 0.80, assessedBy: 3 },
      { patientId: 17, chiefComplaint: 'Rectal bleeding', symptoms: 'Bright red blood per rectum, dizziness', painLevel: 3, onsetTime: '6 hours', triageLevel: '2-Emergency', aiRecommendation: 'CBC, type and screen, GI consult', aiConfidence: 0.88, assessedBy: 3 }
    ]);
    console.log('Triage assessments seeded');

    // 16 Vital Signs
    await VitalSign.bulkCreate([
      { patientId: 1, heartRate: 110, bloodPressureSystolic: 160, bloodPressureDiastolic: 95, temperature: 98.6, respiratoryRate: 22, oxygenSaturation: 94, glucoseLevel: 120, weight: 185, height: 70, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 2, heartRate: 98, bloodPressureSystolic: 130, bloodPressureDiastolic: 80, temperature: 103.2, respiratoryRate: 24, oxygenSaturation: 95, glucoseLevel: 110, weight: 140, height: 64, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 3, heartRate: 88, bloodPressureSystolic: 140, bloodPressureDiastolic: 85, temperature: 98.4, respiratoryRate: 18, oxygenSaturation: 98, glucoseLevel: 105, weight: 200, height: 72, alertLevel: 'Normal', recordedBy: 3 },
      { patientId: 4, heartRate: 105, bloodPressureSystolic: 125, bloodPressureDiastolic: 78, temperature: 100.8, respiratoryRate: 20, oxygenSaturation: 97, glucoseLevel: 95, weight: 130, height: 63, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 5, heartRate: 102, bloodPressureSystolic: 145, bloodPressureDiastolic: 90, temperature: 98.2, respiratoryRate: 22, oxygenSaturation: 96, glucoseLevel: 450, weight: 210, height: 68, alertLevel: 'Critical', recordedBy: 3 },
      { patientId: 6, heartRate: 78, bloodPressureSystolic: 120, bloodPressureDiastolic: 75, temperature: 98.6, respiratoryRate: 16, oxygenSaturation: 99, glucoseLevel: 100, weight: 145, height: 66, alertLevel: 'Normal', recordedBy: 3 },
      { patientId: 7, heartRate: 95, bloodPressureSystolic: 155, bloodPressureDiastolic: 92, temperature: 99.1, respiratoryRate: 28, oxygenSaturation: 88, glucoseLevel: 130, weight: 175, height: 69, alertLevel: 'Critical', recordedBy: 3 },
      { patientId: 8, heartRate: 115, bloodPressureSystolic: 90, bloodPressureDiastolic: 55, temperature: 98.8, respiratoryRate: 26, oxygenSaturation: 93, glucoseLevel: 108, weight: 155, height: 65, alertLevel: 'Critical', recordedBy: 3 },
      { patientId: 9, heartRate: 75, bloodPressureSystolic: 128, bloodPressureDiastolic: 82, temperature: 98.4, respiratoryRate: 16, oxygenSaturation: 99, glucoseLevel: 102, weight: 190, height: 71, alertLevel: 'Normal', recordedBy: 3 },
      { patientId: 10, heartRate: 92, bloodPressureSystolic: 118, bloodPressureDiastolic: 72, temperature: 99.5, respiratoryRate: 18, oxygenSaturation: 97, glucoseLevel: 88, weight: 135, height: 62, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 11, heartRate: 88, bloodPressureSystolic: 185, bloodPressureDiastolic: 110, temperature: 98.6, respiratoryRate: 20, oxygenSaturation: 96, glucoseLevel: 140, weight: 170, height: 67, alertLevel: 'Critical', recordedBy: 3 },
      { patientId: 12, heartRate: 80, bloodPressureSystolic: 115, bloodPressureDiastolic: 70, temperature: 98.2, respiratoryRate: 16, oxygenSaturation: 99, glucoseLevel: 98, weight: 125, height: 64, alertLevel: 'Normal', recordedBy: 3 },
      { patientId: 13, heartRate: 90, bloodPressureSystolic: 132, bloodPressureDiastolic: 80, temperature: 98.6, respiratoryRate: 18, oxygenSaturation: 98, glucoseLevel: 110, weight: 180, height: 71, alertLevel: 'Normal', recordedBy: 3 },
      { patientId: 14, heartRate: 85, bloodPressureSystolic: 138, bloodPressureDiastolic: 86, temperature: 100.2, respiratoryRate: 18, oxygenSaturation: 98, glucoseLevel: 105, weight: 150, height: 66, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 15, heartRate: 120, bloodPressureSystolic: 142, bloodPressureDiastolic: 88, temperature: 98.4, respiratoryRate: 24, oxygenSaturation: 99, glucoseLevel: 115, weight: 160, height: 68, alertLevel: 'Warning', recordedBy: 3 },
      { patientId: 16, heartRate: 72, bloodPressureSystolic: 110, bloodPressureDiastolic: 68, temperature: 98.6, respiratoryRate: 14, oxygenSaturation: 100, glucoseLevel: 95, weight: 120, height: 63, alertLevel: 'Normal', recordedBy: 3 }
    ]);
    console.log('Vital signs seeded');

    // 16 Symptom Analyses
    await SymptomAnalysis.bulkCreate([
      { patientId: 1, symptoms: 'Crushing chest pain, diaphoresis, nausea', duration: '30 minutes', severity: 'Critical', bodyRegion: 'Chest', aiDiagnosis: 'Acute Myocardial Infarction', differentialDiagnosis: 'STEMI, Unstable angina, Aortic dissection', recommendedTests: 'Troponin, ECG, CXR', urgencyScore: 9.5 },
      { patientId: 2, symptoms: 'High fever, productive cough, fatigue, body aches', duration: '3 days', severity: 'Moderate', bodyRegion: 'Respiratory', aiDiagnosis: 'Community-acquired pneumonia', differentialDiagnosis: 'Pneumonia, Bronchitis, Influenza, COVID-19', recommendedTests: 'CXR, CBC, Blood culture, Respiratory panel', urgencyScore: 6.0 },
      { patientId: 3, symptoms: 'Right arm pain, swelling, deformity, numbness in fingers', duration: '1 hour', severity: 'Moderate', bodyRegion: 'Upper Extremity', aiDiagnosis: 'Distal radius fracture', differentialDiagnosis: 'Fracture, Dislocation, Severe sprain', recommendedTests: 'X-ray right wrist/forearm', urgencyScore: 5.5 },
      { patientId: 4, symptoms: 'RLQ abdominal pain, nausea, fever, loss of appetite', duration: '6 hours', severity: 'Severe', bodyRegion: 'Abdomen', aiDiagnosis: 'Acute appendicitis', differentialDiagnosis: 'Appendicitis, Ovarian cyst, Ectopic pregnancy', recommendedTests: 'CT abdomen, CBC, CRP, Pregnancy test', urgencyScore: 8.0 },
      { patientId: 5, symptoms: 'Confusion, extreme thirst, polyuria, blurred vision', duration: '2 hours', severity: 'Severe', bodyRegion: 'Systemic', aiDiagnosis: 'Diabetic ketoacidosis', differentialDiagnosis: 'DKA, HHS, Hypoglycemia', recommendedTests: 'BMP, ABG, Serum ketones, Urinalysis', urgencyScore: 8.5 },
      { patientId: 6, symptoms: 'Unilateral throbbing headache, visual aura, nausea', duration: '4 hours', severity: 'Moderate', bodyRegion: 'Head', aiDiagnosis: 'Migraine with aura', differentialDiagnosis: 'Migraine, Tension headache, Subarachnoid hemorrhage', recommendedTests: 'CT head if new onset, Neurological exam', urgencyScore: 5.0 },
      { patientId: 7, symptoms: 'Severe dyspnea, wheezing, productive cough, accessory muscle use', duration: '1 day', severity: 'Severe', bodyRegion: 'Respiratory', aiDiagnosis: 'COPD exacerbation', differentialDiagnosis: 'COPD exacerbation, Heart failure, Pneumonia', recommendedTests: 'ABG, CXR, CBC, BNP', urgencyScore: 8.0 },
      { patientId: 8, symptoms: 'Facial swelling, urticaria, throat tightness, wheezing', duration: '20 minutes', severity: 'Critical', bodyRegion: 'Systemic', aiDiagnosis: 'Anaphylaxis', differentialDiagnosis: 'Anaphylaxis, Angioedema, Severe allergic reaction', recommendedTests: 'Tryptase level, Monitor airway', urgencyScore: 9.8 },
      { patientId: 9, symptoms: 'Lower back pain, muscle spasm, pain with movement', duration: '2 days', severity: 'Mild', bodyRegion: 'Spine', aiDiagnosis: 'Acute lumbar strain', differentialDiagnosis: 'Muscle strain, Herniated disc, Spinal stenosis', recommendedTests: 'X-ray if trauma, MRI if neurological symptoms', urgencyScore: 3.0 },
      { patientId: 10, symptoms: 'Intractable vomiting, dehydration, abdominal cramping', duration: '12 hours', severity: 'Moderate', bodyRegion: 'Abdomen', aiDiagnosis: 'Acute gastroenteritis with dehydration', differentialDiagnosis: 'Gastroenteritis, Food poisoning, Gastroparesis', recommendedTests: 'BMP, CBC, Stool studies', urgencyScore: 5.5 },
      { patientId: 11, symptoms: 'Right-sided weakness, facial droop, slurred speech', duration: '45 minutes', severity: 'Critical', bodyRegion: 'Neurological', aiDiagnosis: 'Acute ischemic stroke', differentialDiagnosis: 'Ischemic stroke, Hemorrhagic stroke, TIA', recommendedTests: 'CT head stat, CTA, CBC, PT/INR', urgencyScore: 10.0 },
      { patientId: 12, symptoms: 'Ankle swelling, bruising, pain with weight bearing', duration: '3 hours', severity: 'Mild', bodyRegion: 'Lower Extremity', aiDiagnosis: 'Grade II ankle sprain', differentialDiagnosis: 'Ankle sprain, Avulsion fracture, Lateral malleolus fracture', recommendedTests: 'X-ray ankle (Ottawa rules)', urgencyScore: 2.5 },
      { patientId: 13, symptoms: 'Deep laceration, active bleeding, exposed tissue', duration: '30 minutes', severity: 'Moderate', bodyRegion: 'Upper Extremity', aiDiagnosis: 'Deep forearm laceration', differentialDiagnosis: 'Simple laceration, Tendon injury, Nerve damage', recommendedTests: 'X-ray for foreign body, Neurovascular assessment', urgencyScore: 5.0 },
      { patientId: 14, symptoms: 'Flank pain, burning urination, blood in urine', duration: '1 day', severity: 'Moderate', bodyRegion: 'Genitourinary', aiDiagnosis: 'Nephrolithiasis', differentialDiagnosis: 'Kidney stone, UTI, Pyelonephritis', recommendedTests: 'UA, CT KUB, CBC, BMP', urgencyScore: 6.0 },
      { patientId: 15, symptoms: 'Palpitations, chest tightness, hyperventilation, trembling', duration: '1 hour', severity: 'Mild', bodyRegion: 'Psychiatric/Cardiac', aiDiagnosis: 'Panic disorder', differentialDiagnosis: 'Panic attack, SVT, Hyperthyroidism, Pheochromocytoma', recommendedTests: 'ECG, TSH, BMP', urgencyScore: 3.5 },
      { patientId: 17, symptoms: 'Rectal bleeding, lightheadedness, fatigue', duration: '6 hours', severity: 'Severe', bodyRegion: 'GI', aiDiagnosis: 'Lower GI bleeding', differentialDiagnosis: 'Diverticular bleed, Hemorrhoids, Colorectal lesion', recommendedTests: 'CBC, Type and screen, CMP, Stool guaiac', urgencyScore: 7.5 }
    ]);
    console.log('Symptom analyses seeded');

    // 16 Priority Queue
    await PriorityQueue.bulkCreate([
      { patientId: 11, priority: 1, queuePosition: 1, estimatedWaitMinutes: 0, department: 'Neurology', status: 'In Progress', aiPriorityReason: 'Acute stroke - time-critical intervention required' },
      { patientId: 8, priority: 1, queuePosition: 2, estimatedWaitMinutes: 0, department: 'Emergency', status: 'In Progress', aiPriorityReason: 'Anaphylaxis - immediate airway management needed' },
      { patientId: 1, priority: 2, queuePosition: 3, estimatedWaitMinutes: 5, department: 'Cardiology', status: 'Called', aiPriorityReason: 'Suspected MI - requires urgent cardiac workup' },
      { patientId: 5, priority: 2, queuePosition: 4, estimatedWaitMinutes: 10, department: 'Internal Medicine', status: 'Waiting', aiPriorityReason: 'DKA - needs immediate insulin and fluid management' },
      { patientId: 4, priority: 2, queuePosition: 5, estimatedWaitMinutes: 15, department: 'Surgery', status: 'Waiting', aiPriorityReason: 'Possible appendicitis - surgical evaluation needed' },
      { patientId: 7, priority: 2, queuePosition: 6, estimatedWaitMinutes: 15, department: 'Pulmonology', status: 'Waiting', aiPriorityReason: 'COPD exacerbation with low O2 sat' },
      { patientId: 17, priority: 2, queuePosition: 7, estimatedWaitMinutes: 20, department: 'GI', status: 'Waiting', aiPriorityReason: 'Active GI bleeding with hemodynamic concerns' },
      { patientId: 2, priority: 3, queuePosition: 8, estimatedWaitMinutes: 30, department: 'Internal Medicine', status: 'Waiting', aiPriorityReason: 'High fever with respiratory symptoms' },
      { patientId: 3, priority: 3, queuePosition: 9, estimatedWaitMinutes: 35, department: 'Orthopedics', status: 'Waiting', aiPriorityReason: 'Possible fracture - needs imaging' },
      { patientId: 13, priority: 3, queuePosition: 10, estimatedWaitMinutes: 40, department: 'Emergency', status: 'Waiting', aiPriorityReason: 'Deep laceration requiring repair' },
      { patientId: 14, priority: 3, queuePosition: 11, estimatedWaitMinutes: 45, department: 'Urology', status: 'Waiting', aiPriorityReason: 'Suspected kidney stone with hematuria' },
      { patientId: 10, priority: 3, queuePosition: 12, estimatedWaitMinutes: 50, department: 'Internal Medicine', status: 'Waiting', aiPriorityReason: 'Dehydration from persistent vomiting' },
      { patientId: 6, priority: 3, queuePosition: 13, estimatedWaitMinutes: 55, department: 'Neurology', status: 'Waiting', aiPriorityReason: 'Migraine with aura - needs neurological assessment' },
      { patientId: 9, priority: 4, queuePosition: 14, estimatedWaitMinutes: 75, department: 'Orthopedics', status: 'Waiting', aiPriorityReason: 'Non-acute back pain, stable condition' },
      { patientId: 12, priority: 4, queuePosition: 15, estimatedWaitMinutes: 80, department: 'Orthopedics', status: 'Waiting', aiPriorityReason: 'Ankle sprain - non-emergent' },
      { patientId: 15, priority: 4, queuePosition: 16, estimatedWaitMinutes: 90, department: 'Psychiatry', status: 'Waiting', aiPriorityReason: 'Panic attack - hemodynamically stable' }
    ]);
    console.log('Priority queue seeded');

    // 16 Doctor Assignments
    await DoctorAssignment.bulkCreate([
      { patientId: 1, doctorName: 'Dr. James Wilson', specialty: 'Cardiology', department: 'Cardiac Care', status: 'In Consultation', aiMatchScore: 0.95, aiMatchReason: 'Chest pain with cardiac risk factors - cardiology expertise needed', room: 'Cardiac Bay 1' },
      { patientId: 2, doctorName: 'Dr. Priya Patel', specialty: 'Internal Medicine', department: 'General ER', status: 'Assigned', aiMatchScore: 0.85, aiMatchReason: 'Febrile illness with respiratory symptoms', room: 'Room 204' },
      { patientId: 3, doctorName: 'Dr. Michael Chen', specialty: 'Orthopedics', department: 'Orthopedic ER', status: 'Assigned', aiMatchScore: 0.92, aiMatchReason: 'Suspected fracture requiring orthopedic evaluation', room: 'Room 301' },
      { patientId: 4, doctorName: 'Dr. Rachel Kim', specialty: 'General Surgery', department: 'Surgical ER', status: 'In Consultation', aiMatchScore: 0.91, aiMatchReason: 'Appendicitis workup requiring surgical assessment', room: 'Room 105' },
      { patientId: 5, doctorName: 'Dr. Ahmed Hassan', specialty: 'Endocrinology', department: 'Internal Medicine', status: 'In Consultation', aiMatchScore: 0.93, aiMatchReason: 'DKA management requires endocrine expertise', room: 'Room 208' },
      { patientId: 7, doctorName: 'Dr. Lisa Thompson', specialty: 'Pulmonology', department: 'Respiratory Care', status: 'In Consultation', aiMatchScore: 0.94, aiMatchReason: 'COPD exacerbation with respiratory failure risk', room: 'Room 110' },
      { patientId: 8, doctorName: 'Dr. Sarah Admin', specialty: 'Emergency Medicine', department: 'Resuscitation', status: 'In Consultation', aiMatchScore: 0.97, aiMatchReason: 'Anaphylaxis requiring immediate EM physician', room: 'Resus Bay 2' },
      { patientId: 11, doctorName: 'Dr. David Park', specialty: 'Neurology', department: 'Stroke Center', status: 'In Consultation', aiMatchScore: 0.98, aiMatchReason: 'Acute stroke - stroke neurologist needed stat', room: 'Stroke Bay 1' },
      { patientId: 6, doctorName: 'Dr. Karen Foster', specialty: 'Neurology', department: 'General ER', status: 'Assigned', aiMatchScore: 0.80, aiMatchReason: 'Migraine assessment, rule out secondary causes', room: 'Room 215' },
      { patientId: 10, doctorName: 'Dr. Robert Lee', specialty: 'Internal Medicine', department: 'General ER', status: 'Assigned', aiMatchScore: 0.82, aiMatchReason: 'GI symptoms with dehydration management', room: 'Room 209' },
      { patientId: 13, doctorName: 'Dr. Jennifer Walsh', specialty: 'Emergency Medicine', department: 'Procedure Room', status: 'Assigned', aiMatchScore: 0.88, aiMatchReason: 'Laceration repair expertise', room: 'Procedure Room 2' },
      { patientId: 14, doctorName: 'Dr. Steven Burke', specialty: 'Urology', department: 'General ER', status: 'Assigned', aiMatchScore: 0.90, aiMatchReason: 'Suspected nephrolithiasis - urology consult', room: 'Room 212' },
      { patientId: 16, doctorName: 'Dr. Maria Santos', specialty: 'Emergency Medicine', department: 'Fast Track', status: 'Completed', aiMatchScore: 0.75, aiMatchReason: 'Minor injury appropriate for fast track', room: 'Fast Track 3' },
      { patientId: 17, doctorName: 'Dr. William Hong', specialty: 'Gastroenterology', department: 'GI Suite', status: 'In Consultation', aiMatchScore: 0.93, aiMatchReason: 'GI bleeding requires gastroenterology evaluation', room: 'Room 106' },
      { patientId: 20, doctorName: 'Dr. Angela Ross', specialty: 'Internal Medicine', department: 'General ER', status: 'In Consultation', aiMatchScore: 0.84, aiMatchReason: 'Multi-system assessment needed', room: 'Room 220' },
      { patientId: 15, doctorName: 'Dr. Daniel Cruz', specialty: 'Psychiatry', department: 'Behavioral Health', status: 'Assigned', aiMatchScore: 0.86, aiMatchReason: 'Panic disorder evaluation and management', room: 'BH Room 1' }
    ]);
    console.log('Doctor assignments seeded');

    // 16 Treatments
    await Treatment.bulkCreate([
      { patientId: 1, diagnosis: 'Acute STEMI', treatmentPlan: 'PCI with stent placement', procedures: 'Cardiac catheterization, Drug-eluting stent', aiRecommendation: 'Dual antiplatelet therapy post-PCI, beta-blocker, ACE inhibitor', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. James Wilson' },
      { patientId: 2, diagnosis: 'Community-acquired pneumonia', treatmentPlan: 'IV antibiotics, supportive care', procedures: 'None', aiRecommendation: 'Azithromycin + Ceftriaxone, IV fluids, monitor respiratory status', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Priya Patel' },
      { patientId: 3, diagnosis: 'Distal radius fracture', treatmentPlan: 'Closed reduction and casting', procedures: 'Conscious sedation, Closed reduction, Short arm cast', aiRecommendation: 'Follow-up in 1 week for repeat films, pain management with acetaminophen/oxycodone', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Michael Chen' },
      { patientId: 4, diagnosis: 'Acute appendicitis', treatmentPlan: 'Appendectomy', procedures: 'Laparoscopic appendectomy', aiRecommendation: 'Pre-op antibiotics, NPO, surgical consult for emergent appendectomy', aiEvidenceLevel: 'High', status: 'Planned', prescribedBy: 'Dr. Rachel Kim' },
      { patientId: 5, diagnosis: 'Diabetic ketoacidosis', treatmentPlan: 'Insulin drip, fluid resuscitation, electrolyte replacement', procedures: 'Central line placement', aiRecommendation: 'Regular insulin drip at 0.1 units/kg/hr, NS bolus then maintenance, potassium replacement', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Ahmed Hassan' },
      { patientId: 6, diagnosis: 'Migraine with aura', treatmentPlan: 'Abortive therapy', procedures: 'None', aiRecommendation: 'Sumatriptan 6mg SC, metoclopramide 10mg IV, dark quiet room', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Karen Foster' },
      { patientId: 7, diagnosis: 'Acute COPD exacerbation', treatmentPlan: 'Bronchodilators, steroids, BiPAP', procedures: 'BiPAP ventilation', aiRecommendation: 'Albuterol/Ipratropium nebs q4h, Methylprednisolone 125mg IV, BiPAP for respiratory support', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Lisa Thompson' },
      { patientId: 8, diagnosis: 'Anaphylaxis', treatmentPlan: 'Epinephrine, antihistamines, steroids, observation', procedures: 'IM Epinephrine administration', aiRecommendation: 'Epinephrine 0.3mg IM, Diphenhydramine 50mg IV, Methylprednisolone 125mg IV, 6hr observation', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Sarah Admin' },
      { patientId: 9, diagnosis: 'Acute lumbar strain', treatmentPlan: 'Conservative management', procedures: 'None', aiRecommendation: 'Cyclobenzaprine 10mg TID, Ibuprofen 600mg TID, physical therapy referral', aiEvidenceLevel: 'Moderate', status: 'Completed', prescribedBy: 'Dr. Karen Foster' },
      { patientId: 10, diagnosis: 'Acute gastroenteritis with dehydration', treatmentPlan: 'IV hydration, antiemetics', procedures: 'IV fluid administration', aiRecommendation: 'Ondansetron 4mg IV, LR 1L bolus then maintenance, advance diet as tolerated', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Robert Lee' },
      { patientId: 11, diagnosis: 'Acute ischemic stroke', treatmentPlan: 'tPA administration, neuro-ICU admission', procedures: 'IV tPA infusion', aiRecommendation: 'Alteplase 0.9mg/kg IV (max 90mg), BP management, neuro checks q15min', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. David Park' },
      { patientId: 12, diagnosis: 'Grade II lateral ankle sprain', treatmentPlan: 'RICE, immobilization, pain management', procedures: 'Air stirrup brace application', aiRecommendation: 'Ice 20min q2h, compression, elevation, crutches, follow-up in 5-7 days', aiEvidenceLevel: 'High', status: 'Completed', prescribedBy: 'Dr. Maria Santos' },
      { patientId: 13, diagnosis: 'Deep forearm laceration', treatmentPlan: 'Wound repair, tetanus prophylaxis', procedures: 'Wound irrigation, Layered suture repair (12 stitches)', aiRecommendation: 'Lidocaine local, irrigate thoroughly, repair in layers, Tdap booster', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Jennifer Walsh' },
      { patientId: 14, diagnosis: 'Nephrolithiasis', treatmentPlan: 'Pain management, hydration, strain urine', procedures: 'None', aiRecommendation: 'Ketorolac 30mg IV, Tamsulosin 0.4mg daily, strain all urine, urology follow-up', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. Steven Burke' },
      { patientId: 16, diagnosis: 'Minor contusion', treatmentPlan: 'Ice, rest, OTC pain relief', procedures: 'None', aiRecommendation: 'Acetaminophen 500mg q6h PRN, ice 20min q2h, activity as tolerated', aiEvidenceLevel: 'High', status: 'Completed', prescribedBy: 'Dr. Maria Santos' },
      { patientId: 17, diagnosis: 'Lower GI hemorrhage', treatmentPlan: 'Fluid resuscitation, blood products, GI evaluation', procedures: 'Blood transfusion, Colonoscopy pending', aiRecommendation: 'Type and cross for 2 units PRBCs, IV PPI, NPO for colonoscopy, GI consult', aiEvidenceLevel: 'High', status: 'In Progress', prescribedBy: 'Dr. William Hong' }
    ]);
    console.log('Treatments seeded');

    // 16 Wait Times
    await WaitTime.bulkCreate([
      { department: 'General ER', currentWaitMinutes: 45, averageWaitMinutes: 35, patientsWaiting: 8, patientsInTreatment: 12, aiPredictedWait: 50, aiPredictionAccuracy: 0.85, peakHour: true, staffOnDuty: 6 },
      { department: 'Cardiac Care', currentWaitMinutes: 10, averageWaitMinutes: 15, patientsWaiting: 2, patientsInTreatment: 4, aiPredictedWait: 12, aiPredictionAccuracy: 0.90, peakHour: false, staffOnDuty: 3 },
      { department: 'Trauma', currentWaitMinutes: 5, averageWaitMinutes: 10, patientsWaiting: 1, patientsInTreatment: 3, aiPredictedWait: 8, aiPredictionAccuracy: 0.88, peakHour: false, staffOnDuty: 4 },
      { department: 'Pediatrics', currentWaitMinutes: 30, averageWaitMinutes: 25, patientsWaiting: 5, patientsInTreatment: 6, aiPredictedWait: 35, aiPredictionAccuracy: 0.82, peakHour: true, staffOnDuty: 3 },
      { department: 'Orthopedics', currentWaitMinutes: 55, averageWaitMinutes: 40, patientsWaiting: 6, patientsInTreatment: 4, aiPredictedWait: 60, aiPredictionAccuracy: 0.80, peakHour: true, staffOnDuty: 2 },
      { department: 'Neurology', currentWaitMinutes: 15, averageWaitMinutes: 20, patientsWaiting: 3, patientsInTreatment: 5, aiPredictedWait: 18, aiPredictionAccuracy: 0.87, peakHour: false, staffOnDuty: 3 },
      { department: 'Respiratory Care', currentWaitMinutes: 20, averageWaitMinutes: 22, patientsWaiting: 4, patientsInTreatment: 7, aiPredictedWait: 25, aiPredictionAccuracy: 0.84, peakHour: false, staffOnDuty: 4 },
      { department: 'Surgical ER', currentWaitMinutes: 25, averageWaitMinutes: 30, patientsWaiting: 3, patientsInTreatment: 5, aiPredictedWait: 28, aiPredictionAccuracy: 0.86, peakHour: false, staffOnDuty: 3 },
      { department: 'Fast Track', currentWaitMinutes: 60, averageWaitMinutes: 45, patientsWaiting: 10, patientsInTreatment: 5, aiPredictedWait: 55, aiPredictionAccuracy: 0.78, peakHour: true, staffOnDuty: 2 },
      { department: 'Behavioral Health', currentWaitMinutes: 40, averageWaitMinutes: 50, patientsWaiting: 4, patientsInTreatment: 3, aiPredictedWait: 45, aiPredictionAccuracy: 0.75, peakHour: false, staffOnDuty: 2 },
      { department: 'Obstetrics', currentWaitMinutes: 15, averageWaitMinutes: 18, patientsWaiting: 2, patientsInTreatment: 4, aiPredictedWait: 15, aiPredictionAccuracy: 0.89, peakHour: false, staffOnDuty: 3 },
      { department: 'Internal Medicine', currentWaitMinutes: 35, averageWaitMinutes: 30, patientsWaiting: 7, patientsInTreatment: 8, aiPredictedWait: 40, aiPredictionAccuracy: 0.83, peakHour: true, staffOnDuty: 4 },
      { department: 'Urology', currentWaitMinutes: 50, averageWaitMinutes: 45, patientsWaiting: 3, patientsInTreatment: 2, aiPredictedWait: 48, aiPredictionAccuracy: 0.81, peakHour: false, staffOnDuty: 1 },
      { department: 'ENT', currentWaitMinutes: 65, averageWaitMinutes: 55, patientsWaiting: 4, patientsInTreatment: 2, aiPredictedWait: 60, aiPredictionAccuracy: 0.79, peakHour: true, staffOnDuty: 1 },
      { department: 'Ophthalmology', currentWaitMinutes: 70, averageWaitMinutes: 60, patientsWaiting: 3, patientsInTreatment: 1, aiPredictedWait: 65, aiPredictionAccuracy: 0.77, peakHour: true, staffOnDuty: 1 },
      { department: 'GI Suite', currentWaitMinutes: 30, averageWaitMinutes: 28, patientsWaiting: 2, patientsInTreatment: 3, aiPredictedWait: 32, aiPredictionAccuracy: 0.85, peakHour: false, staffOnDuty: 2 }
    ]);
    console.log('Wait times seeded');

    // 16 Medical Histories
    await MedicalHistory.bulkCreate([
      { patientId: 1, condition: 'Hypertension', diagnosedDate: '2018-05-10', status: 'Chronic', treatment: 'Lisinopril 10mg daily', physician: 'Dr. Martin', hospital: 'Mass General', aiRiskAssessment: 'High cardiovascular risk with current presentation' },
      { patientId: 1, condition: 'Hyperlipidemia', diagnosedDate: '2019-02-15', status: 'Active', treatment: 'Atorvastatin 40mg daily', physician: 'Dr. Martin', hospital: 'Mass General', aiRiskAssessment: 'Contributing factor to cardiac risk profile' },
      { patientId: 3, condition: 'Osteoporosis', diagnosedDate: '2020-08-22', status: 'Active', treatment: 'Alendronate 70mg weekly, Calcium/Vit D', physician: 'Dr. Stevens', hospital: 'Brigham & Women', aiRiskAssessment: 'Increased fracture risk from minor trauma' },
      { patientId: 5, condition: 'Type 2 Diabetes', diagnosedDate: '2015-03-12', status: 'Chronic', treatment: 'Metformin 1000mg BID, Insulin Glargine 20u QHS', physician: 'Dr. Hassan', hospital: 'Beth Israel', aiRiskAssessment: 'High risk for DKA, monitor glucose closely' },
      { patientId: 5, condition: 'Peripheral Neuropathy', diagnosedDate: '2021-06-08', status: 'Chronic', treatment: 'Gabapentin 300mg TID', physician: 'Dr. Hassan', hospital: 'Beth Israel', aiRiskAssessment: 'Complication of diabetes, affects sensation' },
      { patientId: 7, condition: 'COPD', diagnosedDate: '2016-11-30', status: 'Chronic', treatment: 'Tiotropium inhaler, Albuterol PRN', physician: 'Dr. Thompson', hospital: 'Mass General', aiRiskAssessment: 'Progressive disease, current exacerbation expected' },
      { patientId: 7, condition: 'Coronary Artery Disease', diagnosedDate: '2019-09-15', status: 'Active', treatment: 'Aspirin, Metoprolol, Isosorbide', physician: 'Dr. Wilson', hospital: 'Mass General', aiRiskAssessment: 'Cardiac risk during respiratory distress' },
      { patientId: 8, condition: 'Asthma', diagnosedDate: '2005-04-18', status: 'Chronic', treatment: 'Fluticasone/Salmeterol, Albuterol PRN', physician: 'Dr. Reed', hospital: 'Children Hospital', aiRiskAssessment: 'Increased risk of severe allergic reactions' },
      { patientId: 11, condition: 'Atrial Fibrillation', diagnosedDate: '2022-01-20', status: 'Active', treatment: 'Warfarin, Metoprolol', physician: 'Dr. Park', hospital: 'Brigham & Women', aiRiskAssessment: 'AFib is a major stroke risk factor' },
      { patientId: 11, condition: 'Hypertension', diagnosedDate: '2010-07-10', status: 'Chronic', treatment: 'Amlodipine 10mg daily', physician: 'Dr. Park', hospital: 'Brigham & Women', aiRiskAssessment: 'Uncontrolled HTN increases stroke risk' },
      { patientId: 14, condition: 'History of Kidney Stones', diagnosedDate: '2023-03-05', status: 'Resolved', treatment: 'Increased hydration, Dietary changes', physician: 'Dr. Burke', hospital: 'Beth Israel', aiRiskAssessment: 'Recurrent stone former, high risk for current episode' },
      { patientId: 17, condition: 'Diverticulosis', diagnosedDate: '2021-10-15', status: 'Active', treatment: 'High fiber diet, Regular colonoscopy', physician: 'Dr. Hong', hospital: 'Mass General', aiRiskAssessment: 'Known diverticular disease - likely source of bleeding' },
      { patientId: 20, condition: 'Hypothyroidism', diagnosedDate: '2019-12-01', status: 'Active', treatment: 'Levothyroxine 75mcg daily', physician: 'Dr. Ross', hospital: 'Newton-Wellesley', aiRiskAssessment: 'Well-controlled on current medication' },
      { patientId: 2, condition: 'Seasonal Allergies', diagnosedDate: '2010-05-01', status: 'Chronic', treatment: 'Cetirizine PRN', physician: 'Dr. Patel', hospital: 'Cambridge Health', aiRiskAssessment: 'Low risk, no interaction with current presentation' },
      { patientId: 15, condition: 'Generalized Anxiety Disorder', diagnosedDate: '2022-06-15', status: 'Active', treatment: 'Sertraline 100mg daily', physician: 'Dr. Cruz', hospital: 'McLean Hospital', aiRiskAssessment: 'History of anxiety - correlates with current panic symptoms' },
      { patientId: 9, condition: 'Herniated Disc L4-L5', diagnosedDate: '2023-01-20', status: 'Resolved', treatment: 'Physical therapy, Epidural injection', physician: 'Dr. Chen', hospital: 'Spaulding Rehab', aiRiskAssessment: 'Previous back injury increases vulnerability to re-injury' }
    ]);
    console.log('Medical histories seeded');

    // 16 Lab Orders
    await LabOrder.bulkCreate([
      { patientId: 1, testName: 'Troponin I', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: '2.5 ng/mL', normalRange: '<0.04 ng/mL', aiInterpretation: 'Significantly elevated - consistent with acute myocardial injury', orderedBy: 'Dr. Wilson' },
      { patientId: 1, testName: '12-Lead ECG', testType: 'Cardiac', urgency: 'STAT', status: 'Completed', results: 'ST elevation in leads II, III, aVF', normalRange: 'Normal sinus rhythm', aiInterpretation: 'Inferior STEMI pattern - activate cath lab', orderedBy: 'Dr. Wilson' },
      { patientId: 2, testName: 'CBC with Differential', testType: 'Blood', urgency: 'Urgent', status: 'Completed', results: 'WBC 15.2, Hgb 13.5, Plt 280', normalRange: 'WBC 4.5-11.0', aiInterpretation: 'Leukocytosis consistent with bacterial infection', orderedBy: 'Dr. Patel' },
      { patientId: 2, testName: 'Chest X-Ray', testType: 'Imaging', urgency: 'Urgent', status: 'Completed', results: 'Right lower lobe consolidation', normalRange: 'Clear lung fields', aiInterpretation: 'Findings consistent with right lower lobe pneumonia', orderedBy: 'Dr. Patel' },
      { patientId: 4, testName: 'CT Abdomen/Pelvis', testType: 'Imaging', urgency: 'STAT', status: 'Completed', results: 'Enlarged appendix 12mm, periappendiceal fat stranding', normalRange: 'Appendix <6mm', aiInterpretation: 'Findings highly suggestive of acute appendicitis', orderedBy: 'Dr. Kim' },
      { patientId: 5, testName: 'Basic Metabolic Panel', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: 'Glucose 450, K 5.8, Na 130, HCO3 12, BUN 35', normalRange: 'Glucose 70-100', aiInterpretation: 'DKA pattern: hyperglycemia, hyperkalemia, acidosis', orderedBy: 'Dr. Hassan' },
      { patientId: 5, testName: 'Arterial Blood Gas', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: 'pH 7.18, pCO2 20, pO2 95, HCO3 10', normalRange: 'pH 7.35-7.45', aiInterpretation: 'Severe metabolic acidosis with respiratory compensation', orderedBy: 'Dr. Hassan' },
      { patientId: 7, testName: 'Arterial Blood Gas', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: 'pH 7.30, pCO2 58, pO2 55, HCO3 28', normalRange: 'pCO2 35-45', aiInterpretation: 'Acute on chronic respiratory acidosis with hypoxemia', orderedBy: 'Dr. Thompson' },
      { patientId: 11, testName: 'CT Head without Contrast', testType: 'Imaging', urgency: 'STAT', status: 'Completed', results: 'No hemorrhage. Hyperdense MCA sign on right', normalRange: 'No acute findings', aiInterpretation: 'No hemorrhage - eligible for tPA. MCA sign suggests large vessel occlusion', orderedBy: 'Dr. Park' },
      { patientId: 11, testName: 'PT/INR', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: 'PT 15.2s, INR 1.3', normalRange: 'PT 11-13.5s, INR <1.1', aiInterpretation: 'Mildly elevated INR - patient on Warfarin. Still eligible for tPA (INR <1.7)', orderedBy: 'Dr. Park' },
      { patientId: 14, testName: 'Urinalysis', testType: 'Urine', urgency: 'Urgent', status: 'Completed', results: 'RBC >50, WBC 5, Nitrite negative, Blood 3+', normalRange: 'RBC 0-3', aiInterpretation: 'Significant hematuria consistent with nephrolithiasis', orderedBy: 'Dr. Burke' },
      { patientId: 14, testName: 'CT KUB', testType: 'Imaging', urgency: 'Urgent', status: 'Completed', results: '6mm stone at right UVJ', normalRange: 'No calculi', aiInterpretation: '6mm stone at UVJ - may pass spontaneously, consider urology consult', orderedBy: 'Dr. Burke' },
      { patientId: 17, testName: 'CBC', testType: 'Blood', urgency: 'STAT', status: 'Completed', results: 'WBC 9.5, Hgb 9.2, Hct 28%, Plt 195', normalRange: 'Hgb 13.5-17.5', aiInterpretation: 'Significant anemia from GI blood loss', orderedBy: 'Dr. Hong' },
      { patientId: 17, testName: 'Type and Screen', testType: 'Blood Bank', urgency: 'STAT', status: 'Completed', results: 'Blood type O+, Antibody screen negative', normalRange: 'N/A', aiInterpretation: 'Ready for transfusion if needed. Compatible blood available', orderedBy: 'Dr. Hong' },
      { patientId: 10, testName: 'BMP', testType: 'Blood', urgency: 'Urgent', status: 'Completed', results: 'Na 132, K 3.2, Cl 95, BUN 28, Cr 1.3', normalRange: 'Na 136-145, K 3.5-5.0', aiInterpretation: 'Hyponatremia and hypokalemia from volume loss, mild AKI', orderedBy: 'Dr. Lee' },
      { patientId: 15, testName: 'ECG', testType: 'Cardiac', urgency: 'Urgent', status: 'Completed', results: 'Sinus tachycardia at 118bpm, no ST changes', normalRange: 'NSR 60-100bpm', aiInterpretation: 'Sinus tachycardia likely from anxiety. No ischemic changes', orderedBy: 'Dr. Cruz' }
    ]);
    console.log('Lab orders seeded');

    // 16 Medications
    await Medication.bulkCreate([
      { patientId: 1, medicationName: 'Aspirin', dosage: '325mg', frequency: 'Once (loading dose)', route: 'Oral', prescribedBy: 'Dr. Wilson', status: 'Active', aiInteractionCheck: 'No significant interactions', aiDosageVerification: 'Appropriate loading dose for ACS' },
      { patientId: 1, medicationName: 'Heparin', dosage: '60 units/kg bolus then 12 units/kg/hr', frequency: 'Continuous', route: 'IV', prescribedBy: 'Dr. Wilson', status: 'Active', aiInteractionCheck: 'Monitor with aspirin for bleeding risk', aiDosageVerification: 'Weight-based dosing appropriate' },
      { patientId: 2, medicationName: 'Ceftriaxone', dosage: '1g', frequency: 'Every 24 hours', route: 'IV', prescribedBy: 'Dr. Patel', status: 'Active', aiInteractionCheck: 'No significant interactions', aiDosageVerification: 'Standard dose for CAP' },
      { patientId: 2, medicationName: 'Azithromycin', dosage: '500mg', frequency: 'Every 24 hours', route: 'IV', prescribedBy: 'Dr. Patel', status: 'Active', aiInteractionCheck: 'QT prolongation risk - monitor ECG', aiDosageVerification: 'Appropriate for atypical coverage' },
      { patientId: 4, medicationName: 'Piperacillin-Tazobactam', dosage: '3.375g', frequency: 'Every 6 hours', route: 'IV', prescribedBy: 'Dr. Kim', status: 'Active', aiInteractionCheck: 'No interactions with current meds', aiDosageVerification: 'Standard pre-op antibiotic for appendicitis' },
      { patientId: 5, medicationName: 'Regular Insulin', dosage: '0.1 units/kg/hr', frequency: 'Continuous', route: 'IV', prescribedBy: 'Dr. Hassan', status: 'Active', aiInteractionCheck: 'Monitor potassium closely', aiDosageVerification: 'Standard DKA protocol dosing' },
      { patientId: 6, medicationName: 'Sumatriptan', dosage: '6mg', frequency: 'Once', route: 'Sublingual', prescribedBy: 'Dr. Foster', status: 'Active', aiInteractionCheck: 'Check for SSRI use - serotonin syndrome risk', aiDosageVerification: 'Appropriate acute migraine dose' },
      { patientId: 7, medicationName: 'Methylprednisolone', dosage: '125mg', frequency: 'Every 6 hours', route: 'IV', prescribedBy: 'Dr. Thompson', status: 'Active', aiInteractionCheck: 'Monitor blood glucose with steroids', aiDosageVerification: 'Standard COPD exacerbation dose' },
      { patientId: 8, medicationName: 'Epinephrine', dosage: '0.3mg', frequency: 'Once (repeat PRN q5-15min)', route: 'IM', prescribedBy: 'Dr. Admin', status: 'Completed', aiInteractionCheck: 'Caution with beta-blockers', aiDosageVerification: 'Standard anaphylaxis dose' },
      { patientId: 8, medicationName: 'Diphenhydramine', dosage: '50mg', frequency: 'Every 6 hours', route: 'IV', prescribedBy: 'Dr. Admin', status: 'Active', aiInteractionCheck: 'Sedation risk', aiDosageVerification: 'Appropriate antihistamine dose' },
      { patientId: 10, medicationName: 'Ondansetron', dosage: '4mg', frequency: 'Every 6 hours PRN', route: 'IV', prescribedBy: 'Dr. Lee', status: 'Active', aiInteractionCheck: 'QT prolongation risk with repeated doses', aiDosageVerification: 'Standard antiemetic dose' },
      { patientId: 11, medicationName: 'Alteplase (tPA)', dosage: '0.9mg/kg (max 90mg)', frequency: 'Once - 10% bolus, 90% over 1hr', route: 'IV', prescribedBy: 'Dr. Park', status: 'Active', aiInteractionCheck: 'HOLD all anticoagulants for 24hrs', aiDosageVerification: 'Standard stroke protocol dosing' },
      { patientId: 13, medicationName: 'Lidocaine 1%', dosage: '10mL', frequency: 'Once (local)', route: 'Topical', prescribedBy: 'Dr. Walsh', status: 'Completed', aiInteractionCheck: 'Check for local anesthetic allergy', aiDosageVerification: 'Safe dose for wound repair' },
      { patientId: 14, medicationName: 'Ketorolac', dosage: '30mg', frequency: 'Every 6 hours', route: 'IV', prescribedBy: 'Dr. Burke', status: 'Active', aiInteractionCheck: 'Avoid with renal impairment - check Cr', aiDosageVerification: 'Standard dose, limit to 5 days' },
      { patientId: 14, medicationName: 'Tamsulosin', dosage: '0.4mg', frequency: 'Once daily', route: 'Oral', prescribedBy: 'Dr. Burke', status: 'Active', aiInteractionCheck: 'May cause orthostatic hypotension', aiDosageVerification: 'Standard dose for stone passage' },
      { patientId: 9, medicationName: 'Cyclobenzaprine', dosage: '10mg', frequency: 'Three times daily', route: 'Oral', prescribedBy: 'Dr. Foster', status: 'Active', aiInteractionCheck: 'Sedation risk, avoid driving', aiDosageVerification: 'Standard muscle relaxant dose' }
    ]);
    console.log('Medications seeded');

    // 16 Discharges
    await Discharge.bulkCreate([
      { patientId: 9, dischargeDate: new Date(), diagnosis: 'Acute lumbar strain', dischargeSummary: 'Patient presented with lower back pain after lifting. Exam showed paravertebral muscle spasm. X-ray negative for fracture. Treated with muscle relaxant and NSAIDs.', followUpInstructions: 'Follow up with PCP in 1 week. Start physical therapy within 2 weeks.', prescriptions: 'Cyclobenzaprine 10mg TID x7 days, Ibuprofen 600mg TID x10 days', aiDischargeNotes: 'Low risk for recurrence with proper body mechanics', aiFollowUpRecommendation: 'Physical therapy evaluation within 2 weeks', dischargedBy: 'Dr. Karen Foster', status: 'Completed', returnPrecautions: 'Return if numbness/weakness in legs, loss of bladder/bowel control, or worsening pain' },
      { patientId: 12, dischargeDate: new Date(), diagnosis: 'Grade II lateral ankle sprain', dischargeSummary: 'Patient sustained ankle injury during sports. X-ray negative for fracture. Applied air stirrup brace. RICE instructions provided.', followUpInstructions: 'Follow up with orthopedics in 5-7 days. Keep brace on when weight bearing.', prescriptions: 'Ibuprofen 400mg TID PRN x7 days', aiDischargeNotes: 'Expected 4-6 week recovery. Gradual return to activities.', aiFollowUpRecommendation: 'Orthopedic follow-up for ligament stability assessment', dischargedBy: 'Dr. Maria Santos', status: 'Completed', returnPrecautions: 'Return if unable to bear weight, significant swelling increase, or numbness in foot' },
      { patientId: 16, dischargeDate: new Date(), diagnosis: 'Minor contusion', dischargeSummary: 'Patient presented with minor bruising. No fracture on exam. Ice and rest recommended.', followUpInstructions: 'Follow up with PCP if not improving in 5-7 days', prescriptions: 'Acetaminophen 500mg q6h PRN', aiDischargeNotes: 'Benign injury, full recovery expected', aiFollowUpRecommendation: 'PCP follow-up only if symptoms persist', dischargedBy: 'Dr. Maria Santos', status: 'Completed', returnPrecautions: 'Return if increasing pain, swelling, or fever' },
      { patientId: 1, diagnosis: 'STEMI - status post PCI', dischargeSummary: 'Pending cardiac recovery', status: 'Pending', aiDischargeNotes: 'Will need cardiac rehab referral', aiFollowUpRecommendation: 'Cardiology follow-up in 1 week, cardiac rehab enrollment', dischargedBy: 'Dr. Wilson' },
      { patientId: 2, diagnosis: 'Community-acquired pneumonia', dischargeSummary: 'Pending antibiotic completion', status: 'Pending', aiDischargeNotes: 'Complete 5-day antibiotic course', aiFollowUpRecommendation: 'PCP follow-up in 3 days, repeat CXR in 6 weeks', dischargedBy: 'Dr. Patel' },
      { patientId: 3, diagnosis: 'Distal radius fracture', dischargeSummary: 'Pending orthopedic follow-up scheduling', status: 'Pending', aiDischargeNotes: 'Cast care instructions needed', aiFollowUpRecommendation: 'Orthopedics in 1 week for repeat films', dischargedBy: 'Dr. Chen' },
      { patientId: 4, diagnosis: 'Acute appendicitis - post appendectomy', dischargeSummary: 'Pending surgical recovery', status: 'Pending', aiDischargeNotes: 'Post-op care instructions needed', aiFollowUpRecommendation: 'Surgery follow-up in 2 weeks', dischargedBy: 'Dr. Kim' },
      { patientId: 5, diagnosis: 'DKA - resolved', dischargeSummary: 'Pending endocrine optimization', status: 'Pending', aiDischargeNotes: 'Diabetes education critical before discharge', aiFollowUpRecommendation: 'Endocrinology in 3 days, diabetes educator referral', dischargedBy: 'Dr. Hassan' },
      { patientId: 6, diagnosis: 'Migraine with aura', dischargeSummary: 'Pending symptom resolution', status: 'Pending', aiDischargeNotes: 'Migraine prevention discussion needed', aiFollowUpRecommendation: 'Neurology follow-up for prevention therapy', dischargedBy: 'Dr. Foster' },
      { patientId: 7, diagnosis: 'COPD exacerbation', dischargeSummary: 'Pending respiratory stabilization', status: 'Pending', aiDischargeNotes: 'Pulmonary rehab referral recommended', aiFollowUpRecommendation: 'Pulmonology in 1 week, pulmonary rehab', dischargedBy: 'Dr. Thompson' },
      { patientId: 8, diagnosis: 'Anaphylaxis', dischargeSummary: 'Pending 6-hour observation', status: 'Pending', aiDischargeNotes: 'EpiPen prescription and allergy referral essential', aiFollowUpRecommendation: 'Allergy/Immunology referral, carry EpiPen at all times', dischargedBy: 'Dr. Admin' },
      { patientId: 10, diagnosis: 'Acute gastroenteritis', dischargeSummary: 'Pending rehydration completion', status: 'Pending', aiDischargeNotes: 'Diet advancement plan needed', aiFollowUpRecommendation: 'PCP in 2-3 days if not fully recovered', dischargedBy: 'Dr. Lee' },
      { patientId: 11, diagnosis: 'Acute ischemic stroke', dischargeSummary: 'Pending neuro-ICU stabilization', status: 'Pending', aiDischargeNotes: 'Stroke rehab assessment needed', aiFollowUpRecommendation: 'Neurology in 1 week, rehabilitation evaluation', dischargedBy: 'Dr. Park' },
      { patientId: 13, diagnosis: 'Deep forearm laceration - repaired', dischargeSummary: 'Pending wound check', status: 'Pending', aiDischargeNotes: 'Wound care instructions, suture removal in 10-14 days', aiFollowUpRecommendation: 'PCP or ER for suture removal in 10-14 days', dischargedBy: 'Dr. Walsh' },
      { patientId: 14, diagnosis: 'Nephrolithiasis', dischargeSummary: 'Pending pain control', status: 'Pending', aiDischargeNotes: 'Strain urine for stone analysis', aiFollowUpRecommendation: 'Urology in 1 week, bring stone for analysis', dischargedBy: 'Dr. Burke' },
      { patientId: 15, diagnosis: 'Panic disorder', dischargeSummary: 'Pending psychiatric evaluation', status: 'Pending', aiDischargeNotes: 'Safety assessment complete, outpatient follow-up', aiFollowUpRecommendation: 'Psychiatry follow-up in 3 days, continue SSRI', dischargedBy: 'Dr. Cruz' }
    ]);
    console.log('Discharges seeded');

    // 16 Emergency Alerts
    await EmergencyAlert.bulkCreate([
      { patientId: 11, alertType: 'Stroke Alert', severity: 'Critical', location: 'Stroke Bay 1', description: 'Acute onset right-sided weakness and aphasia. Last known well 45 min ago. tPA window open.', aiAssessment: 'Large vessel occlusion suspected. tPA eligible. Consider thrombectomy.', aiRecommendedResponse: 'Activate stroke team, CT/CTA stat, prepare tPA', status: 'Responding', triggeredBy: 'Dr. Park' },
      { patientId: 8, alertType: 'Code Blue', severity: 'Critical', location: 'Resus Bay 2', description: 'Anaphylaxis with airway compromise. Epinephrine administered. Monitoring closely.', aiAssessment: 'Severe anaphylaxis. Risk of biphasic reaction in 4-8 hours.', aiRecommendedResponse: 'Secure airway, continuous monitoring, epinephrine drip ready', status: 'Responding', triggeredBy: 'Dr. Admin' },
      { patientId: 1, alertType: 'STEMI Alert', severity: 'Critical', location: 'Cardiac Bay 1', description: 'Inferior STEMI on ECG. Troponin elevated. Door-to-balloon time target: 90 min.', aiAssessment: 'Acute inferior STEMI. High mortality risk without intervention.', aiRecommendedResponse: 'Activate cath lab, dual antiplatelet, heparin bolus', status: 'Responding', triggeredBy: 'Dr. Wilson' },
      { alertType: 'Code Red', severity: 'High', location: 'Kitchen - Floor 2', description: 'Fire alarm activated in kitchen area. Smoke detected by sensors.', aiAssessment: 'Potential fire hazard. Evacuate adjacent areas.', aiRecommendedResponse: 'Fire team respond, evaluate for evacuation, check patients on Floor 2', status: 'Resolved', triggeredBy: 'Facilities', resolvedBy: 'Fire Team', resolvedAt: new Date() },
      { alertType: 'Code Yellow', severity: 'Medium', location: 'ER Main Entrance', description: 'Multiple casualties incoming from MVA. ETA 10 minutes. 4 patients expected.', aiAssessment: 'Mass casualty preparation needed. Activate surge protocol.', aiRecommendedResponse: 'Clear trauma bays, page trauma team, notify OR, activate MCI protocol', status: 'Active', triggeredBy: 'EMS Dispatch' },
      { patientId: 7, alertType: 'Code Blue', severity: 'Critical', location: 'Room 110', description: 'COPD patient with worsening respiratory failure. SpO2 dropping below 85%.', aiAssessment: 'Impending respiratory arrest. May need intubation.', aiRecommendedResponse: 'Respiratory team stat, prepare for intubation, increase BiPAP settings', status: 'Responding', triggeredBy: 'Nurse Maria' },
      { alertType: 'Code White', severity: 'Medium', location: 'Behavioral Health Room 3', description: 'Agitated patient threatening staff. De-escalation attempted.', aiAssessment: 'Behavioral emergency. Risk of harm to patient and staff.', aiRecommendedResponse: 'Security respond, behavioral health team, consider chemical restraint', status: 'Resolved', triggeredBy: 'Nurse Johnson', resolvedBy: 'Security Team', resolvedAt: new Date() },
      { alertType: 'Trauma Alert', severity: 'High', location: 'Trauma Bay 1', description: 'Pedestrian struck by vehicle. GCS 12. Suspected pelvic and femur fractures.', aiAssessment: 'Polytrauma patient. High risk for hemorrhagic shock.', aiRecommendedResponse: 'Trauma team activation, blood products on standby, CT pan-scan', status: 'Active', triggeredBy: 'EMS' },
      { patientId: 5, alertType: 'Code Yellow', severity: 'High', location: 'Room 208', description: 'DKA patient with potassium level 6.2. ECG changes noted.', aiAssessment: 'Hyperkalemia with cardiac effects. Life-threatening.', aiRecommendedResponse: 'Calcium gluconate stat, insulin/glucose, kayexalate, continuous cardiac monitoring', status: 'Responding', triggeredBy: 'Dr. Hassan' },
      { alertType: 'Code Orange', severity: 'Medium', location: 'Hazmat Bay', description: 'Patient arriving with chemical exposure. Unknown substance.', aiAssessment: 'Chemical exposure - decontamination required before treatment.', aiRecommendedResponse: 'Activate hazmat team, prepare decontamination area, identify substance', status: 'Active', triggeredBy: 'EMS' },
      { alertType: 'Code Red', severity: 'Low', location: 'Parking Garage Level 2', description: 'Minor vehicle fire in parking structure. Fire department en route.', aiAssessment: 'Low risk to hospital operations. Monitor smoke direction.', aiRecommendedResponse: 'Redirect traffic, close parking level 2, monitor HVAC systems', status: 'Resolved', triggeredBy: 'Security', resolvedBy: 'Fire Department', resolvedAt: new Date() },
      { patientId: 17, alertType: 'Code Yellow', severity: 'High', location: 'Room 106', description: 'GI bleed patient with hemoglobin dropping. Currently 9.2 and trending down.', aiAssessment: 'Active hemorrhage. May need emergent transfusion.', aiRecommendedResponse: 'Transfuse 2 units PRBCs, notify GI for emergent endoscopy', status: 'Responding', triggeredBy: 'Dr. Hong' },
      { alertType: 'Code White', severity: 'Low', location: 'Waiting Room', description: 'Verbal altercation between family members in waiting area.', aiAssessment: 'Low severity behavioral incident. De-escalation should suffice.', aiRecommendedResponse: 'Security presence, separate individuals, offer chaplain services', status: 'Resolved', triggeredBy: 'Reception', resolvedBy: 'Security', resolvedAt: new Date() },
      { alertType: 'Trauma Alert', severity: 'Critical', location: 'Helipad', description: 'Helicopter incoming with burn victim. 40% BSA burns. ETA 5 minutes.', aiAssessment: 'Severe burn patient. High risk for airway compromise and fluid loss.', aiRecommendedResponse: 'Burn team activation, prepare Parkland formula fluids, intubation equipment ready', status: 'Active', triggeredBy: 'Flight Medic' },
      { alertType: 'STEMI Alert', severity: 'High', location: 'EMS Bay', description: 'Incoming 65yo male with chest pain and ST elevation on field ECG. ETA 8 min.', aiAssessment: 'Field STEMI activation. Prepare for direct to cath lab.', aiRecommendedResponse: 'Cath lab standby, pre-register patient, cardiology team notified', status: 'Active', triggeredBy: 'Paramedic Unit 12' },
      { patientId: 20, alertType: 'Code Yellow', severity: 'Medium', location: 'Room 220', description: 'Patient with new onset confusion and fever. Concern for sepsis.', aiAssessment: 'Possible sepsis. Start sepsis bundle within 1 hour.', aiRecommendedResponse: 'Blood cultures x2, lactate, broad spectrum antibiotics, 30mL/kg fluid bolus', status: 'Active', triggeredBy: 'Dr. Ross' }
    ]);
    console.log('Emergency alerts seeded');

    // 16 Bed Management
    await BedManagement.bulkCreate([
      { bedNumber: 'ER-101', ward: 'Emergency', department: 'General ER', status: 'Occupied', patientId: 2, bedType: 'Standard', floor: 1, aiOptimalAssignment: 'Appropriate - general medicine patient in standard bed' },
      { bedNumber: 'ER-102', ward: 'Emergency', department: 'General ER', status: 'Occupied', patientId: 10, bedType: 'Standard', floor: 1, aiOptimalAssignment: 'Appropriate - GI patient near bathroom facilities' },
      { bedNumber: 'ER-103', ward: 'Emergency', department: 'General ER', status: 'Available', bedType: 'Standard', floor: 1, aiOptimalAssignment: 'Available for next general admission' },
      { bedNumber: 'CB-201', ward: 'Cardiac', department: 'Cardiac Care', status: 'Occupied', patientId: 1, bedType: 'ICU', floor: 2, aiOptimalAssignment: 'Critical cardiac patient in monitored ICU bed' },
      { bedNumber: 'CB-202', ward: 'Cardiac', department: 'Cardiac Care', status: 'Available', bedType: 'ICU', floor: 2, aiOptimalAssignment: 'Reserve for incoming STEMI patient' },
      { bedNumber: 'TB-301', ward: 'Trauma', department: 'Trauma', status: 'Occupied', patientId: 3, bedType: 'Trauma', floor: 3, aiOptimalAssignment: 'Trauma patient with orthopedic injury' },
      { bedNumber: 'TB-302', ward: 'Trauma', department: 'Trauma', status: 'Reserved', bedType: 'Trauma', floor: 3, aiOptimalAssignment: 'Reserved for incoming trauma from MVA' },
      { bedNumber: 'RB-101', ward: 'Resuscitation', department: 'Resuscitation', status: 'Occupied', patientId: 8, bedType: 'ICU', floor: 1, aiOptimalAssignment: 'Anaphylaxis patient requires resuscitation bay' },
      { bedNumber: 'RB-102', ward: 'Resuscitation', department: 'Resuscitation', status: 'Occupied', patientId: 11, bedType: 'ICU', floor: 1, aiOptimalAssignment: 'Stroke patient requires high-acuity monitoring' },
      { bedNumber: 'SB-401', ward: 'Surgery', department: 'Surgical ER', status: 'Occupied', patientId: 4, bedType: 'Standard', floor: 4, aiOptimalAssignment: 'Pre-op appendicitis patient near OR' },
      { bedNumber: 'NB-201', ward: 'Neurology', department: 'Neurology', status: 'Occupied', patientId: 6, bedType: 'Standard', floor: 2, aiOptimalAssignment: 'Migraine patient in quiet ward' },
      { bedNumber: 'PB-501', ward: 'Pulmonary', department: 'Respiratory Care', status: 'Occupied', patientId: 7, bedType: 'ICU', floor: 5, aiOptimalAssignment: 'COPD patient requires respiratory ICU monitoring' },
      { bedNumber: 'IM-301', ward: 'Internal Medicine', department: 'Internal Medicine', status: 'Occupied', patientId: 5, bedType: 'Standard', floor: 3, aiOptimalAssignment: 'DKA patient with insulin drip - needs frequent monitoring' },
      { bedNumber: 'FT-101', ward: 'Fast Track', department: 'Fast Track', status: 'Available', bedType: 'Standard', floor: 1, aiOptimalAssignment: 'Available for minor injury/illness' },
      { bedNumber: 'FT-102', ward: 'Fast Track', department: 'Fast Track', status: 'Cleaning', bedType: 'Standard', floor: 1, aiOptimalAssignment: 'Being prepared for next patient' },
      { bedNumber: 'ISO-601', ward: 'Isolation', department: 'Infection Control', status: 'Maintenance', bedType: 'Isolation', floor: 6, aiOptimalAssignment: 'Under maintenance - HVAC repair for negative pressure' }
    ]);
    console.log('Bed management seeded');

    // 16 Patient Flow records
    const today = new Date().toISOString().split('T')[0];
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    await PatientFlow.bulkCreate([
      { date: today, hour: 0, totalAdmissions: 3, totalDischarges: 1, averageWaitTime: 25, averageTreatmentTime: 90, occupancyRate: 65, department: 'General ER', aiPredictedAdmissions: 4, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Current staffing adequate for overnight', aiBottleneckAnalysis: 'No significant bottlenecks at this hour' },
      { date: today, hour: 4, totalAdmissions: 2, totalDischarges: 2, averageWaitTime: 15, averageTreatmentTime: 75, occupancyRate: 55, department: 'General ER', aiPredictedAdmissions: 2, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Minimum staffing sufficient', aiBottleneckAnalysis: 'Low volume period - good time for shift change' },
      { date: today, hour: 8, totalAdmissions: 8, totalDischarges: 3, averageWaitTime: 35, averageTreatmentTime: 95, occupancyRate: 72, department: 'General ER', aiPredictedAdmissions: 10, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Increase staffing for morning surge', aiBottleneckAnalysis: 'Triage becoming bottleneck - add triage nurse' },
      { date: today, hour: 12, totalAdmissions: 15, totalDischarges: 6, averageWaitTime: 55, averageTreatmentTime: 110, occupancyRate: 85, department: 'General ER', aiPredictedAdmissions: 18, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Peak approaching - call in additional staff', aiBottleneckAnalysis: 'Lab turnaround time causing delays. Fast track overwhelmed.' },
      { date: today, hour: 14, totalAdmissions: 20, totalDischarges: 8, averageWaitTime: 70, averageTreatmentTime: 120, occupancyRate: 92, department: 'General ER', aiPredictedAdmissions: 22, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'CRITICAL: Maximum staffing needed. Consider diversion.', aiBottleneckAnalysis: 'Bed shortage is primary bottleneck. Expedite discharges.' },
      { date: today, hour: 8, totalAdmissions: 5, totalDischarges: 2, averageWaitTime: 20, averageTreatmentTime: 80, occupancyRate: 70, department: 'Cardiac Care', aiPredictedAdmissions: 6, aiPredictedPeakHour: 10, aiStaffingRecommendation: 'Adequate cardiac team coverage', aiBottleneckAnalysis: 'Cath lab availability may become issue' },
      { date: today, hour: 12, totalAdmissions: 4, totalDischarges: 1, averageWaitTime: 10, averageTreatmentTime: 150, occupancyRate: 80, department: 'Trauma', aiPredictedAdmissions: 6, aiPredictedPeakHour: 18, aiStaffingRecommendation: 'Trauma team adequate, backup surgeon available', aiBottleneckAnalysis: 'OR availability could be limiting factor' },
      { date: today, hour: 10, totalAdmissions: 6, totalDischarges: 2, averageWaitTime: 40, averageTreatmentTime: 85, occupancyRate: 75, department: 'Orthopedics', aiPredictedAdmissions: 8, aiPredictedPeakHour: 16, aiStaffingRecommendation: 'Need additional orthopedic consultant after 2pm', aiBottleneckAnalysis: 'Imaging wait times causing delays' },
      { date: yesterday, hour: 14, totalAdmissions: 22, totalDischarges: 10, averageWaitTime: 65, averageTreatmentTime: 105, occupancyRate: 90, department: 'General ER', aiPredictedAdmissions: 20, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Was understaffed yesterday - adjust today', aiBottleneckAnalysis: 'Yesterday peak was significant - similar expected today' },
      { date: yesterday, hour: 18, totalAdmissions: 18, totalDischarges: 12, averageWaitTime: 50, averageTreatmentTime: 100, occupancyRate: 82, department: 'General ER', aiPredictedAdmissions: 15, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Evening shift maintained good flow', aiBottleneckAnalysis: 'Post-peak recovery went well' },
      { date: yesterday, hour: 22, totalAdmissions: 5, totalDischarges: 8, averageWaitTime: 20, averageTreatmentTime: 85, occupancyRate: 60, department: 'General ER', aiPredictedAdmissions: 4, aiPredictedPeakHour: 14, aiStaffingRecommendation: 'Night shift staffing appropriate', aiBottleneckAnalysis: 'Good discharge flow in evening reduced occupancy' },
      { date: today, hour: 8, totalAdmissions: 3, totalDischarges: 1, averageWaitTime: 30, averageTreatmentTime: 60, occupancyRate: 60, department: 'Fast Track', aiPredictedAdmissions: 8, aiPredictedPeakHour: 13, aiStaffingRecommendation: 'Fast track needs additional PA after 11am', aiBottleneckAnalysis: 'Volume increasing - prepare for afternoon rush' },
      { date: today, hour: 10, totalAdmissions: 4, totalDischarges: 2, averageWaitTime: 45, averageTreatmentTime: 120, occupancyRate: 68, department: 'Neurology', aiPredictedAdmissions: 5, aiPredictedPeakHour: 12, aiStaffingRecommendation: 'Adequate neurology coverage', aiBottleneckAnalysis: 'CT scanner wait time causing assessment delays' },
      { date: today, hour: 12, totalAdmissions: 2, totalDischarges: 0, averageWaitTime: 20, averageTreatmentTime: 90, occupancyRate: 50, department: 'Behavioral Health', aiPredictedAdmissions: 4, aiPredictedPeakHour: 20, aiStaffingRecommendation: 'Psychiatric coverage needed for evening peak', aiBottleneckAnalysis: 'Inpatient bed availability for psychiatric admissions is limited' },
      { date: today, hour: 6, totalAdmissions: 2, totalDischarges: 1, averageWaitTime: 18, averageTreatmentTime: 70, occupancyRate: 45, department: 'Respiratory Care', aiPredictedAdmissions: 5, aiPredictedPeakHour: 10, aiStaffingRecommendation: 'Respiratory therapist coverage adequate', aiBottleneckAnalysis: 'No current bottlenecks' },
      { date: today, hour: 10, totalAdmissions: 3, totalDischarges: 1, averageWaitTime: 25, averageTreatmentTime: 95, occupancyRate: 55, department: 'Surgical ER', aiPredictedAdmissions: 5, aiPredictedPeakHour: 15, aiStaffingRecommendation: 'Surgical team adequate, OR rooms available', aiBottleneckAnalysis: 'Pre-op lab clearance causing minor delays' }
    ]);
    console.log('Patient flow seeded');

    console.log('\n✅ All data seeded successfully!');
    console.log('Login credentials:');
    console.log('  Admin: admin@ertriage.com / password123');
    console.log('  Doctor: doctor@ertriage.com / password123');
    console.log('  Nurse: nurse@ertriage.com / password123');
    console.log('  Reception: reception@ertriage.com / password123');

    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
